### ISSUE TITLE
Add Travis Test Integration 

### ISSUE THREAD

**Issue by nammn** [adejoux/kitchen-wpar#6]
It would be great to add the following additions

- Travis Test integration of the ruby tests

- Travis Test Link in the README.md

**Comment by adejoux** [comment]
It's a great point. I need to make it work with an AIX environment so it can take some time on my side.

**Comment by nammn** [comment]
The Ruby Spec tests should be able to run independently of Aix in GitHub 👍

**Comment by adejoux** [comment]
Yes but it would need to simulate aix behavior to be relevant. It's possible, let me think about it. :)
